Enhance test client
wirenboard/python-mqtt-rpc pull request #3
Opened 2022-11-04 18:30 UTC by sikmir

Usage example:
```sh
$ mqtt-rpc-client -d db_logger -s history -m get_channels | tr "'" '"' | jq -r '.channels|keys|.[]'
...
wb-msw-v3_31/Humidity
wb-msw-v3_31/Temperature
...
```

2022-11-11 06:32 UTC, webconn requested changes
Я б ещё сразу подумал в сторону подключения через UNIX-сокет по умолчанию, как тут: https://github.com/wirenboard/wb-diag-collect/blob/master/wb/diag/rpc_server.py

2022-11-11 06:32 UTC, webconn commented on bin/mqtt-rpc-client
> +    import paho.mqtt.client as mosquitto
Можно сразу избавляться от `mosquitto`, всё равно пользоваться им больше не стоит

2022-11-11 06:32 UTC, webconn commented on bin/mqtt-rpc-client
> +        default="db_logger",
Я бы не стал тут делать допущения насчёт значений по умолчанию

2022-11-11 06:32 UTC, webconn commented on bin/mqtt-rpc-client
> +        "-a", "--args", dest="args", type=str, help="Method arguments", default="{}"
Тут можно сделать магию, написав `type=json.loads`, тогда оно сразу распарсится

2022-11-11 08:20 UTC, sikmir commented on bin/mqtt-rpc-client
> +    import paho.mqtt.client as mosquitto
убрал

2022-11-11 08:21 UTC, sikmir commented on bin/mqtt-rpc-client
> +        default="db_logger",
убрал дефолты

2022-11-11 08:22 UTC, sikmir commented on bin/mqtt-rpc-client
> +        "-a", "--args", dest="args", type=str, help="Method arguments", default="{}"
fixed

2022-11-11 10:52 UTC, sikmir commented
> Я б ещё сразу подумал в сторону подключения через UNIX-сокет по умолчанию, как тут: https://github.com/wirenboard/wb-diag-collect/blob/master/wb/diag/rpc_server.py

Заменил на одну опцию `-m, --mqtt_url`.
Например:
* `mqtt-tcp://user:pass@localhost:1883`
* `unix:///var/run/mosquitto/mosquitto.sock`

2022-11-14 10:37 UTC, KraPete requested changes

2022-11-14 10:37 UTC, KraPete commented on debian/changelog
> +  * Enhance test client
Можно конкретики?

2022-11-14 10:37 UTC, KraPete commented on debian/control
> +Depends: python3, ${misc:Depends}, ${shlibs:Depends}, python3-json-rpc, python3-paho-mqtt, python3-mqttrpc
python3-paho-socket ?

2022-11-14 13:43 UTC, sikmir commented on debian/control
> +Depends: python3, ${misc:Depends}, ${shlibs:Depends}, python3-json-rpc, python3-paho-mqtt, python3-mqttrpc
Добавил

2022-11-14 13:46 UTC, sikmir commented on debian/changelog
> +  * Enhance test client
Переформулировал с точки зрения пользователя

2022-11-14 15:01 UTC, KraPete approved these changes

2022-11-18 13:52 UTC, merged